title: Neeraja S Kumar
description: A clean, minimalist Jekyll site for GitHub Pages.
lang: en

url: ""
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - docs/
  - test/
  - _posts/
  - _pages/
  - _projects/
  - _news/
  - _teachings/
  - _books/
  - _bibliography/
  - readme_preview/
  - lighthouse_results/